create_clock -name CLK_200M_P -period 5.000 -waveform {0 2.500} [get_ports CLK_200M_P]

set_property PACKAGE_PIN AC18 [get_ports CLK_200M_P]
set_property IOSTANDARD LVDS [get_ports CLK_200M_P]
set_property PACKAGE_PIN AD18 [get_ports CLK_200M_N]
set_property IOSTANDARD LVDS [get_ports CLK_200M_N]

set_property PACKAGE_PIN W26 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property PACKAGE_PIN V21 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

set_property SLEW FAST [get_ports uart_txd]
set_property DRIVE 16 [get_ports uart_txd]
set_property PULLUP true [get_ports uart_txd]
set_property PULLUP true [get_ports uart_rxd]

set_property PACKAGE_PIN W13 [get_ports RSTN]
set_property IOSTANDARD LVCMOS18 [get_ports RSTN]

# set_property IOSTANDARD LVCMOS18 [get_ports {led_out[7]}]
# set_property IOSTANDARD LVCMOS18 [get_ports {led_out[6]}]
# set_property IOSTANDARD LVCMOS18 [get_ports {led_out[5]}]
# set_property IOSTANDARD LVCMOS18 [get_ports {led_out[4]}]
# set_property IOSTANDARD LVCMOS18 [get_ports {led_out[3]}]
# set_property IOSTANDARD LVCMOS18 [get_ports {led_out[2]}]
# set_property IOSTANDARD LVCMOS18 [get_ports {led_out[1]}]
# set_property IOSTANDARD LVCMOS18 [get_ports {led_out[0]}]
# set_property PACKAGE_PIN W23 [get_ports {led_out[7]}]
# set_property PACKAGE_PIN AB26 [get_ports {led_out[6]}]
# set_property PACKAGE_PIN Y25 [get_ports {led_out[5]}]
# set_property PACKAGE_PIN AA23 [get_ports {led_out[4]}]
# set_property PACKAGE_PIN Y23 [get_ports {led_out[3]}]
# set_property PACKAGE_PIN Y22 [get_ports {led_out[2]}]
# set_property PACKAGE_PIN AE21 [get_ports {led_out[1]}]
# set_property PACKAGE_PIN AF24 [get_ports {led_out[0]}]
